# Development tools configuration for mise

[tools]
python = "3.12"
uv = "latest"
gcloud = "latest"

# Aqua packages for additional tools
"aqua:slack.com/slack-cli" = "3.4.0"

[env]
PYTHONPATH = "."
GOOGLE_APPLICATION_CREDENTIALS = "./service-account-key.json"