name: Copilot Setup Steps

on:
  workflow_call:
    secrets:
      COPILOT_GITHUB_TOKEN:
        required: true

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.COPILOT_GITHUB_TOKEN }}

      - name: Setup mise and install dependencies
        uses: jdxcode/mise-action@v2
        with:
          version: latest
          install: true
          cache: true